#!/usr/bin/env bash

## Runs devtools::check() and checks for ERROR or WARNING in the output log.
## Exits with code 0 if there are none, with 1 otherwise.

checkdir=`mktemp -d`

cat <<EOF | R --no-save
library(devtools)
library(romero.gateway)

devtools::check(check_dir = '$checkdir')

EOF

if grep -q 'ERROR\|WARNING' $checkdir/romero.gateway.Rcheck/00check.log; then
  exit 1
else
  exit 0
fi
