#!/usr/bin/env bash

OMERO_HOST=${OMERO_HOST:-localhost}
OMERO_PORT=${OMERO_PORT:-4064}
OMERO_USER=${OMERO_USER:-root}
OMERO_PASS=${OMERO_PASS:-omero}

cat <<EOF | R --no-save
library(devtools)
library(romero.gateway)

# Retry connecting until server is up and running
for (i in 1:60) {
  server <- tryCatch(
            {
              server <- OMEROServer(host='$OMERO_HOST', port=$OMERO_PORT, username='$OMERO_USER', password='$OMERO_PASS')
              server <- connect(server)
              return(server)
            },
            error=function(cond) {
              Sys.sleep(10)
              return(NA)
            },
            warning=function(cond) {
            },
            finally={
            }
          )
  if (!is.na(server))
    break
}

devtools::test()
EOF
