#!/usr/bin/env bash

OMERO_SERVER_HOST=${OMERO_SERVER_HOST:-omero}
OMERO_SERVER_PORT=${OMERO_SERVER_PORT:-4064}
OMERO_SERVER_USER=${OMERO_SERVER_USER:-root}
OMERO_SERVER_PASS=${OMERO_SERVER_PASS:-omero}

cat <<EOF | R --no-save
library(devtools)
library(romero.gateway)

# Retry connecting until server is up and running
for (i in 1:60) {
  server <- tryCatch(
            {
              server <- OMEROServer(
                host='$OMERO_SERVER_HOST',
                port=$OMERO_SERVER_PORT,
                username='$OMERO_SERVER_USER',
                password='$OMERO_SERVER_PASS')
              server <- connect(server)
              return(server)
            },
            error=function(cond) {
              Sys.sleep(10)
              return(NA)
            },
            warning=function(cond) {
            },
            finally={
            }
          )
  if (!is.na(server))
    break
}

devtools::test()
EOF
