#!/usr/bin/env bash

## Check CRAN compatibilty with devtools::check()

checkdir=`mktemp -d`
cat <<EOF | R --no-save
library(devtools)
library(romero.gateway)

devtools::check(check_dir = '$checkdir')

EOF

if grep -q 'ERROR\|WARNING' $checkdir/romero.gateway.Rcheck/00check.log; then
  echo "Error/Warnings found with devtools::check()"
  exit 1
else
  exit 0
fi

## Run integration tests when test server is ready

OMERO_SERVER_HOST=${OMERO_SERVER_HOST:-omero}
OMERO_SERVER_PORT=${OMERO_SERVER_PORT:-4064}
OMERO_SERVER_USER=${OMERO_SERVER_USER:-root}
OMERO_SERVER_PASS=${OMERO_SERVER_PASS:-omero}

cat <<EOF | R --no-save
library(devtools)
library(romero.gateway)

# Retry connecting until server is up and running
ready <- FALSE
for (i in 1:60) {
  server <- tryCatch(
            {
              server <- OMEROServer(
                host='$OMERO_SERVER_HOST',
                port=as.integer($OMERO_SERVER_PORT),
                username='$OMERO_SERVER_USER',
                password='$OMERO_SERVER_PASS')
              connect(server)
            },
            error=function(cond) {
              return(NULL)
            },
            warning=function(cond) {
            },
            finally={
            }
          )
  if (!is.null(server)) {
    ready <- TRUE
    disconnect(server)
    break
  }
  else {
    Sys.sleep(10)
  }
}

if (ready) {
  devtools::test()
} else {
  message("Could not get connection to server")
}

EOF
